apiVersion: v1
kind: Service
metadata:
  name: customers
  labels:
    app: customers
  namespace: development
spec:
  selector:
    app: customers
  ports:
    - port: 80
      name: http
      targetPort: 3000
