apiVersion: v1
kind: Service
metadata:
  name: web-frontend
  labels:
    app: web-frontend
  namespace: development
spec:
  selector:
    app: web-frontend
  ports:
    - port: 80
      name: http
      targetPort: 8080